customer:
    label: Customer
    span: full
    view:
        form:
            fields:
                name:
                    type: text
                    label: Name
                    span: auto
                surname:
                    type: text
                    label: Name
                    span: auto
                email:
                    type: text
                    label: Email
        toolbarButtons: create|link
    manage:
        form: $/cargie/booking/models/customer/fields.yaml
        list: $/cargie/booking/models/customer/columns.yaml
rooms:
    label: Rooms
    list: ~/plugins/cargie/booking/models/bookingroom/columns.yaml
    form: ~/plugins/cargie/booking/models/bookingroom/fields.yaml
    emptyMessage: Booking has no rooms
    view:
        toolbarButtons: create|delete
# booked_rooms:
#     label: Booked Rooms
#     view:
#         toolbarButtons: add|remove
#         list:
#             columns:
#                 name:
#                     label: Room
#                     type: text
#                 pivot[start_at]:
#                     label: Check In
#                     type: date
#                 pivot[end_at]:
#                     label: Check Out
#                     type: date
#                 pivot[adult]:
#                     label: Adult
#                     type: number
#                 pivot[children]:
#                     label: Children
#                     type: number