# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder Room Types

# Attribute name
nameFrom: name

# Model Class name
modelClass: Cargie\Booking\Models\RoomType

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar